<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\Api\V1\AuthApiController;
use App\Controllers\Api\V1\CallControlApiController;
use App\Controllers\Api\V1\CrmApiController;
use App\Controllers\Api\V1\PbxApiController;
use App\Controllers\Api\V1\ResourceApiController;
use App\Controllers\Api\V1\SecurityApiController;
use App\Controllers\ApiTokenController;
use App\Controllers\BillingController;
use App\Controllers\CompanyController;
use App\Controllers\CrmController;
use App\Controllers\DashboardController;
use App\Controllers\HomeController;
use App\Controllers\LicensingController;
use App\Controllers\PbxController;
use App\Controllers\ProvisioningController;
use App\Controllers\QueueController;
use App\Controllers\RealtimeController;
use App\Controllers\SecurityController;
use App\Controllers\WebRtcController;
use App\Core\Response;

$router = $app->router();

$router->get('/', [HomeController::class, 'index']);
$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->post('/logout', [AuthController::class, 'logout'], ['auth']);
$router->get('/settings/profile', [AuthController::class, 'profile'], ['auth']);
$router->post('/settings/language', [AuthController::class, 'updateLanguage'], ['auth']);
$router->get('/settings/api-tokens', [ApiTokenController::class, 'index'], ['auth']);
$router->post('/settings/api-tokens/store', [ApiTokenController::class, 'store'], ['auth']);
$router->post('/settings/api-tokens/revoke', [ApiTokenController::class, 'revoke'], ['auth']);
$router->get('/dashboard', [DashboardController::class, 'index'], ['auth', 'tenant']);
$router->get('/docs/openapi.yaml', static fn ($request): Response => new Response((string) file_get_contents(base_path('docs/openapi.yaml')), 200, ['Content-Type' => 'application/yaml']));

$router->post('/api/v1/auth/token', [AuthApiController::class, 'token']);
$router->get('/api/v1/auth/me', [AuthApiController::class, 'me']);
$router->post('/api/v1/auth/revoke', [AuthApiController::class, 'revoke']);
$router->delete('/api/v1/auth/token', [AuthApiController::class, 'revoke']);
$router->get('/api/v1/companies', [ResourceApiController::class, 'companies']);
$router->get('/api/v1/users', [ResourceApiController::class, 'users']);
$router->get('/api/v1/extensions', [ResourceApiController::class, 'extensions']);
$router->get('/api/v1/ringgroups', [ResourceApiController::class, 'ringgroups']);
$router->get('/api/v1/ivr', [ResourceApiController::class, 'ivr']);
$router->get('/api/v1/trunks', [ResourceApiController::class, 'trunks']);
$router->get('/api/v1/recordings', [ResourceApiController::class, 'recordings']);
$router->get('/api/v1/provisioning/devices', [ResourceApiController::class, 'provisioningDevices']);
$router->get('/api/v1/provisioning/templates', [ResourceApiController::class, 'provisioningTemplates']);
$router->get('/api/v1/provisioning/phonebooks', [ResourceApiController::class, 'provisioningPhonebooks']);
$router->get('/api/v1/crm/contacts', [ResourceApiController::class, 'crmContacts']);
$router->get('/api/v1/crm/contacts/lookup', [CrmApiController::class, 'lookupContact']);
$router->post('/api/v1/crm/contacts', [CrmApiController::class, 'storeContact']);
$router->put('/api/v1/crm/contacts', [CrmApiController::class, 'updateContact']);
$router->delete('/api/v1/crm/contacts', [CrmApiController::class, 'deleteContact']);
$router->get('/api/v1/crm/accounts', [ResourceApiController::class, 'crmAccounts']);
$router->post('/api/v1/crm/accounts', [CrmApiController::class, 'storeAccount']);
$router->put('/api/v1/crm/accounts', [CrmApiController::class, 'updateAccount']);
$router->delete('/api/v1/crm/accounts', [CrmApiController::class, 'deleteAccount']);
$router->get('/api/v1/crm/activities', [ResourceApiController::class, 'crmActivities']);
$router->get('/api/v1/crm/calls', [ResourceApiController::class, 'crmCalls']);
$router->get('/api/v1/pbx/ami/status', [PbxApiController::class, 'amiStatus']);
$router->post('/api/v1/calls/hold', [CallControlApiController::class, 'hold']);
$router->post('/api/v1/calls/unhold', [CallControlApiController::class, 'unhold']);
$router->post('/api/v1/calls/transfer', [CallControlApiController::class, 'transfer']);
$router->post('/api/v1/calls/hangup', [CallControlApiController::class, 'hangup']);
$router->post('/api/v1/calls/park', [CallControlApiController::class, 'park']);
$router->post('/api/v1/calls/pickup', [CallControlApiController::class, 'pickup']);
$router->get('/api/v1/security/fail2ban/status', [SecurityApiController::class, 'fail2banStatus']);
$router->get('/api/v1/security/bans', [SecurityApiController::class, 'bans']);
$router->get('/api/v1/security/events', [SecurityApiController::class, 'events']);
$router->post('/api/v1/security/ban', [SecurityApiController::class, 'ban']);
$router->post('/api/v1/security/unban', [SecurityApiController::class, 'unban']);
$router->get('/api/crm/contacts', [ResourceApiController::class, 'crmContacts']);
$router->get('/api/crm/contacts/lookup', [CrmApiController::class, 'lookupContact']);
$router->post('/api/crm/contacts', [CrmApiController::class, 'storeContact']);
$router->put('/api/crm/contacts', [CrmApiController::class, 'updateContact']);
$router->delete('/api/crm/contacts', [CrmApiController::class, 'deleteContact']);
$router->get('/api/crm/accounts', [ResourceApiController::class, 'crmAccounts']);
$router->post('/api/crm/accounts', [CrmApiController::class, 'storeAccount']);
$router->put('/api/crm/accounts', [CrmApiController::class, 'updateAccount']);
$router->delete('/api/crm/accounts', [CrmApiController::class, 'deleteAccount']);
$router->get('/api/crm/activities', [ResourceApiController::class, 'crmActivities']);
$router->get('/api/crm/calls', [ResourceApiController::class, 'crmCalls']);
$router->get('/api/pbx/ami/status', [PbxApiController::class, 'amiStatus']);
$router->get('/api/security/fail2ban/status', [SecurityApiController::class, 'fail2banStatus']);
$router->get('/api/security/bans', [SecurityApiController::class, 'bans']);
$router->get('/api/security/events', [SecurityApiController::class, 'events']);
$router->post('/api/security/ban', [SecurityApiController::class, 'ban']);
$router->post('/api/security/unban', [SecurityApiController::class, 'unban']);
$router->post('/api/v1/pbx/originate', [PbxApiController::class, 'originate']);
$router->post('/api/pbx/originate', [PbxApiController::class, 'originate']);
$router->get('/api/v1/queues', [ResourceApiController::class, 'queues']);
$router->get('/api/v1/queue-agents', [ResourceApiController::class, 'queueAgents']);
$router->get('/api/v1/queue-events', [ResourceApiController::class, 'queueEvents']);
$router->get('/api/v1/queue-metrics', [ResourceApiController::class, 'queueMetrics']);
$router->get('/api/v1/resellers', [ResourceApiController::class, 'resellers']);
$router->get('/api/v1/billing/subscriptions', [ResourceApiController::class, 'billingSubscriptions']);
$router->get('/api/v1/billing/invoices', [ResourceApiController::class, 'billingInvoices']);
$router->get('/api/v1/billing/usage', [ResourceApiController::class, 'billingUsage']);
$router->post('/api/v1/billing/webhook', [BillingController::class, 'webhook']);
$router->get('/api/v1/webrtc/bootstrap', [WebRtcController::class, 'bootstrap'], ['auth', 'tenant']);
$router->get('/api/v1/webrtc/config', [WebRtcController::class, 'config'], ['auth', 'tenant']);
$router->get('/api/v1/webrtc/token', [WebRtcController::class, 'token'], ['auth', 'tenant']);
$router->get('/api/v1/webrtc/status', [WebRtcController::class, 'status']);
$router->post('/api/v1/webrtc/preferences', [WebRtcController::class, 'preferences'], ['auth', 'tenant']);
$router->post('/api/v1/webrtc/presence', [WebRtcController::class, 'presence'], ['auth', 'tenant']);
$router->post('/api/v1/webrtc/events', [WebRtcController::class, 'event']);
$router->get('/api/v1/realtime/token', [RealtimeController::class, 'token'], ['auth', 'tenant']);
$router->get('/api/v1/realtime/status', [RealtimeController::class, 'status'], ['auth', 'tenant']);

$router->get('/companies', [CompanyController::class, 'index'], ['auth', 'role:super-admin']);
$router->get('/companies/create', [CompanyController::class, 'create'], ['auth', 'role:super-admin']);
$router->post('/companies/store', [CompanyController::class, 'store'], ['auth', 'role:super-admin']);
$router->get('/companies/show', [CompanyController::class, 'show'], ['auth', 'role:super-admin']);
$router->get('/companies/edit', [CompanyController::class, 'edit'], ['auth', 'role:super-admin']);
$router->post('/companies/update', [CompanyController::class, 'update'], ['auth', 'role:super-admin']);
$router->post('/companies/delete', [CompanyController::class, 'destroy'], ['auth', 'role:super-admin']);
$router->get('/companies/dashboard', [CompanyController::class, 'dashboard'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);

$router->get('/licensing', [LicensingController::class, 'dashboard'], ['auth', 'role:super-admin']);
$router->get('/licensing/plans', [LicensingController::class, 'plans'], ['auth', 'role:super-admin']);
$router->get('/licensing/plans/create', [LicensingController::class, 'createPlan'], ['auth', 'role:super-admin']);
$router->post('/licensing/plans/store', [LicensingController::class, 'storePlan'], ['auth', 'role:super-admin']);
$router->get('/licensing/plans/edit', [LicensingController::class, 'editPlan'], ['auth', 'role:super-admin']);
$router->post('/licensing/plans/update', [LicensingController::class, 'updatePlan'], ['auth', 'role:super-admin']);
$router->post('/licensing/plans/delete', [LicensingController::class, 'deletePlan'], ['auth', 'role:super-admin']);
$router->get('/licensing/features', [LicensingController::class, 'features'], ['auth', 'role:super-admin']);
$router->get('/licensing/features/create', [LicensingController::class, 'createFeature'], ['auth', 'role:super-admin']);
$router->post('/licensing/features/store', [LicensingController::class, 'storeFeature'], ['auth', 'role:super-admin']);
$router->get('/licensing/features/edit', [LicensingController::class, 'editFeature'], ['auth', 'role:super-admin']);
$router->post('/licensing/features/update', [LicensingController::class, 'updateFeature'], ['auth', 'role:super-admin']);
$router->post('/licensing/features/delete', [LicensingController::class, 'deleteFeature'], ['auth', 'role:super-admin']);
$router->get('/licensing/licenses', [LicensingController::class, 'licenses'], ['auth', 'role:super-admin']);
$router->get('/licensing/licenses/create', [LicensingController::class, 'createLicense'], ['auth', 'role:super-admin']);
$router->post('/licensing/licenses/store', [LicensingController::class, 'storeLicense'], ['auth', 'role:super-admin']);
$router->get('/licensing/licenses/edit', [LicensingController::class, 'editLicense'], ['auth', 'role:super-admin']);
$router->post('/licensing/licenses/update', [LicensingController::class, 'updateLicense'], ['auth', 'role:super-admin']);
$router->post('/licensing/licenses/delete', [LicensingController::class, 'deleteLicense'], ['auth', 'role:super-admin']);

$router->get('/billing', [BillingController::class, 'dashboard'], ['auth', 'role:super-admin,reseller,admin-empresa']);
$router->get('/billing/resellers', [BillingController::class, 'resellers'], ['auth', 'role:super-admin']);
$router->post('/billing/resellers/store', [BillingController::class, 'storeReseller'], ['auth', 'role:super-admin']);
$router->get('/billing/tenants', [BillingController::class, 'tenants'], ['auth', 'role:super-admin,reseller']);
$router->post('/billing/tenants/assign', [BillingController::class, 'assignTenant'], ['auth', 'role:super-admin,reseller']);
$router->post('/billing/tenants/suspend', [BillingController::class, 'suspendTenant'], ['auth', 'role:super-admin,reseller']);
$router->post('/billing/tenants/reactivate', [BillingController::class, 'reactivateTenant'], ['auth', 'role:super-admin,reseller']);
$router->get('/billing/subscriptions', [BillingController::class, 'subscriptions'], ['auth', 'role:super-admin,reseller']);
$router->post('/billing/subscriptions/store', [BillingController::class, 'storeSubscription'], ['auth', 'role:super-admin,reseller']);
$router->get('/billing/invoices', [BillingController::class, 'invoices'], ['auth', 'role:super-admin,reseller']);
$router->get('/billing/usage', [BillingController::class, 'usage'], ['auth', 'role:super-admin,reseller']);

$router->get('/crm', [CrmController::class, 'index'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/contacts', [CrmController::class, 'contactsIndex'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/activity', [CrmController::class, 'activityIndex'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/contacts/create', [CrmController::class, 'createContact'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/contacts/store', [CrmController::class, 'storeContact'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/contacts/show', [CrmController::class, 'showContact'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/contacts/edit', [CrmController::class, 'editContact'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/contacts/update', [CrmController::class, 'updateContact'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/contacts/delete', [CrmController::class, 'deleteContact'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/contacts/call', [CrmController::class, 'clickToCall'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/accounts/create', [CrmController::class, 'createAccount'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/accounts/store', [CrmController::class, 'storeAccount'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/accounts/show', [CrmController::class, 'showAccount'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/crm/accounts/edit', [CrmController::class, 'editAccount'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/accounts/update', [CrmController::class, 'updateAccount'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/accounts/delete', [CrmController::class, 'deleteAccount'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/crm/activity/note', [CrmController::class, 'addNote'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);

$router->get('/pbx', [PbxController::class, 'dashboard'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/extensions', [PbxController::class, 'extensions'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/extensions/create', [PbxController::class, 'createExtension'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/extensions/store', [PbxController::class, 'storeExtension'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/extensions/edit', [PbxController::class, 'editExtension'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/extensions/update', [PbxController::class, 'updateExtension'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/extensions/regenerate-credentials', [PbxController::class, 'regenerateExtensionCredentials'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/ami/settings', [PbxController::class, 'saveAmiSettings'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/originate', [PbxController::class, 'originate'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/extensions/delete', [PbxController::class, 'deleteExtension'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/recordings', [PbxController::class, 'recordings'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/recordings/play', [PbxController::class, 'playRecording'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/recordings/download', [PbxController::class, 'downloadRecording'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/ring-groups', [PbxController::class, 'ringGroups'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/ring-groups/create', [PbxController::class, 'createRingGroup'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/ring-groups/store', [PbxController::class, 'storeRingGroup'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/ring-groups/edit', [PbxController::class, 'editRingGroup'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/ring-groups/update', [PbxController::class, 'updateRingGroup'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/ring-groups/delete', [PbxController::class, 'deleteRingGroup'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/ivrs', [PbxController::class, 'ivrs'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/ivrs/create', [PbxController::class, 'createIvr'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/ivrs/store', [PbxController::class, 'storeIvr'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/ivrs/edit', [PbxController::class, 'editIvr'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/ivrs/update', [PbxController::class, 'updateIvr'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/ivrs/delete', [PbxController::class, 'deleteIvr'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/trunks', [PbxController::class, 'trunks'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/trunks/create', [PbxController::class, 'createTrunk'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/trunks/store', [PbxController::class, 'storeTrunk'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/trunks/edit', [PbxController::class, 'editTrunk'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/trunks/update', [PbxController::class, 'updateTrunk'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/trunks/delete', [PbxController::class, 'deleteTrunk'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/inbound-routes', [PbxController::class, 'inboundRoutes'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/inbound-routes/create', [PbxController::class, 'createInboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/inbound-routes/store', [PbxController::class, 'storeInboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/inbound-routes/edit', [PbxController::class, 'editInboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/inbound-routes/update', [PbxController::class, 'updateInboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/inbound-routes/delete', [PbxController::class, 'deleteInboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/outbound-routes', [PbxController::class, 'outboundRoutes'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/outbound-routes/create', [PbxController::class, 'createOutboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/outbound-routes/store', [PbxController::class, 'storeOutboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/outbound-routes/edit', [PbxController::class, 'editOutboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/outbound-routes/update', [PbxController::class, 'updateOutboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/pbx/outbound-routes/delete', [PbxController::class, 'deleteOutboundRoute'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/pbx/transports', [PbxController::class, 'transports'], ['auth', 'role:super-admin']);
$router->get('/pbx/transports/create', [PbxController::class, 'createTransport'], ['auth', 'role:super-admin']);
$router->post('/pbx/transports/store', [PbxController::class, 'storeTransport'], ['auth', 'role:super-admin']);
$router->get('/pbx/transports/edit', [PbxController::class, 'editTransport'], ['auth', 'role:super-admin']);
$router->post('/pbx/transports/update', [PbxController::class, 'updateTransport'], ['auth', 'role:super-admin']);
$router->post('/pbx/transports/delete', [PbxController::class, 'deleteTransport'], ['auth', 'role:super-admin']);
$router->get('/pbx/realtime', [PbxController::class, 'realtime'], ['auth', 'role:super-admin']);

$router->get('/security', [SecurityController::class, 'index'], ['auth', 'role:super-admin,admin-empresa']);
$router->get('/security/attacks', [SecurityController::class, 'attacks'], ['auth', 'role:super-admin,admin-empresa']);
$router->get('/security/bans', [SecurityController::class, 'bans'], ['auth', 'role:super-admin,admin-empresa']);
$router->get('/security/fail2ban', [SecurityController::class, 'fail2ban'], ['auth', 'role:super-admin,admin-empresa']);
$router->get('/security/firewall', [SecurityController::class, 'firewall'], ['auth', 'role:super-admin,admin-empresa']);
$router->get('/security/whitelist', [SecurityController::class, 'whitelist'], ['auth', 'role:super-admin,admin-empresa']);
$router->get('/security/blacklist', [SecurityController::class, 'blacklist'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/settings', [SecurityController::class, 'saveSettings'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/ban', [SecurityController::class, 'ban'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/unban', [SecurityController::class, 'unban'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/fail2ban/restart', [SecurityController::class, 'restartFail2ban'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/fail2ban/reload', [SecurityController::class, 'reloadFail2ban'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/firewall/block', [SecurityController::class, 'firewallBlock'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/firewall/unblock', [SecurityController::class, 'firewallUnblock'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/firewall/persist', [SecurityController::class, 'persistFirewall'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/whitelist/store', [SecurityController::class, 'storeWhitelist'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/whitelist/delete', [SecurityController::class, 'deleteWhitelist'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/blacklist/store', [SecurityController::class, 'storeBlacklist'], ['auth', 'role:super-admin,admin-empresa']);
$router->post('/security/blacklist/delete', [SecurityController::class, 'deleteBlacklist'], ['auth', 'role:super-admin,admin-empresa']);

$router->get('/softphone', [WebRtcController::class, 'softphone'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/softphone/settings', [WebRtcController::class, 'saveSettings'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/softphone/enable-endpoint', [WebRtcController::class, 'enableEndpoint'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);

$router->get('/call-center', [QueueController::class, 'index'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/call-center/queues/create', [QueueController::class, 'create'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/call-center/queues/store', [QueueController::class, 'store'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/call-center/queues/edit', [QueueController::class, 'edit'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/call-center/queues/update', [QueueController::class, 'update'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/call-center/queues/delete', [QueueController::class, 'destroy'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/call-center/agents/store', [QueueController::class, 'storeAgent'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/call-center/agents/action', [QueueController::class, 'agentAction'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/call-center/wallboard', [QueueController::class, 'wallboard'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);

$router->get('/provisioning', [ProvisioningController::class, 'index'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/provisioning/devices/create', [ProvisioningController::class, 'createDevice'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/devices/store', [ProvisioningController::class, 'storeDevice'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/provisioning/devices/edit', [ProvisioningController::class, 'editDevice'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/devices/update', [ProvisioningController::class, 'updateDevice'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/devices/delete', [ProvisioningController::class, 'deleteDevice'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/devices/reboot', [ProvisioningController::class, 'rebootDevice'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/devices/regenerate-token', [ProvisioningController::class, 'regenerateToken'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/provisioning/devices/config', [ProvisioningController::class, 'previewConfig'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/provisioning/templates/create', [ProvisioningController::class, 'createTemplate'], ['auth', 'tenant', 'role:super-admin']);
$router->post('/provisioning/templates/store', [ProvisioningController::class, 'storeTemplate'], ['auth', 'tenant', 'role:super-admin']);
$router->get('/provisioning/templates/edit', [ProvisioningController::class, 'editTemplate'], ['auth', 'tenant', 'role:super-admin']);
$router->post('/provisioning/templates/update', [ProvisioningController::class, 'updateTemplate'], ['auth', 'tenant', 'role:super-admin']);
$router->post('/provisioning/templates/delete', [ProvisioningController::class, 'deleteTemplate'], ['auth', 'tenant', 'role:super-admin']);
$router->get('/provisioning/phonebooks/create', [ProvisioningController::class, 'createPhonebook'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/phonebooks/store', [ProvisioningController::class, 'storePhonebook'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/provisioning/phonebooks/edit', [ProvisioningController::class, 'editPhonebook'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/phonebooks/update', [ProvisioningController::class, 'updatePhonebook'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->post('/provisioning/phonebooks/delete', [ProvisioningController::class, 'deletePhonebook'], ['auth', 'tenant', 'role:super-admin,admin-empresa']);
$router->get('/provisioning/config', [ProvisioningController::class, 'config']);
$router->get('/provisioning/{tenant}/{mac}/phonebook', [ProvisioningController::class, 'phonebookByPath']);
$router->get('/provisioning/{tenant}/{mac}', [ProvisioningController::class, 'configByPath']);
