<?php

declare(strict_types=1);

return [
    [
        'id' => 'home',
        'label_key' => 'menu.sections.home',
        'icon' => 'home',
        'default_open' => true,
        'items' => [
            [
                'id' => 'dashboard',
                'label_key' => 'menu.dashboard',
                'path' => '/dashboard',
                'icon' => 'grid',
                'roles' => ['super-admin', 'reseller', 'admin-empresa'],
                'keywords' => ['inicio', 'overview', 'resumen'],
            ],
            [
                'id' => 'system_status',
                'label_key' => 'menu.system_status',
                'path' => '/pbx/realtime',
                'icon' => 'pulse',
                'roles' => ['super-admin'],
                'permission' => 'pbx.view',
                'keywords' => ['health', 'status', 'realtime'],
            ],
            [
                'id' => 'my_company',
                'label_key' => 'menu.my_company',
                'path' => '/companies/dashboard',
                'icon' => 'tenant',
                'roles' => ['admin-empresa'],
                'company_only' => true,
            ],
        ],
    ],
    [
        'id' => 'platform',
        'label_key' => 'menu.sections.platform',
        'icon' => 'platform',
        'items' => [
            [
                'id' => 'companies',
                'label_key' => 'menu.companies',
                'path' => '/companies',
                'icon' => 'building',
                'roles' => ['super-admin'],
            ],
            [
                'id' => 'tenants',
                'label_key' => 'menu.tenants',
                'path' => '/billing/tenants',
                'icon' => 'tenant',
                'roles' => ['super-admin', 'reseller'],
            ],
            [
                'id' => 'licensing',
                'label_key' => 'menu.licensing',
                'path' => '/licensing',
                'icon' => 'license',
                'roles' => ['super-admin'],
                'badge' => 'expired_licenses',
                'badge_tone' => 'danger',
            ],
            [
                'id' => 'settings',
                'label_key' => 'menu.settings',
                'path' => '/settings/profile',
                'icon' => 'settings',
                'roles' => ['super-admin', 'reseller', 'admin-empresa'],
            ],
        ],
    ],
    [
        'id' => 'pbx',
        'label_key' => 'menu.sections.pbx',
        'icon' => 'sip',
        'badge' => 'extensions_online',
        'badge_tone' => 'on',
        'default_open' => true,
        'items' => [
            [
                'id' => 'extensions',
                'label_key' => 'menu.extensions',
                'path' => '/pbx/extensions',
                'icon' => 'extension',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
                'badge' => 'extensions_online',
                'badge_tone' => 'on',
            ],
            [
                'id' => 'softphone',
                'label_key' => 'menu.softphone',
                'path' => '/softphone',
                'icon' => 'call',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'trunks',
                'label_key' => 'menu.trunks',
                'path' => '/pbx/trunks',
                'icon' => 'trunk',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'inbound_routes',
                'label_key' => 'menu.inbound_routes',
                'path' => '/pbx/inbound-routes',
                'icon' => 'arrow-in',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'outbound_routes',
                'label_key' => 'menu.outbound_routes',
                'path' => '/pbx/outbound-routes',
                'icon' => 'arrow-out',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'ivrs',
                'label_key' => 'menu.ivr',
                'path' => '/pbx/ivrs',
                'icon' => 'menu-tree',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'ring_groups',
                'label_key' => 'menu.ring_groups',
                'path' => '/pbx/ring-groups',
                'icon' => 'ring-group',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'recordings',
                'label_key' => 'menu.recordings',
                'path' => '/pbx/recordings',
                'icon' => 'recordings',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
        ],
    ],
    [
        'id' => 'call_center',
        'label_key' => 'menu.sections.call_center',
        'icon' => 'queue',
        'items' => [
            [
                'id' => 'queues',
                'label_key' => 'menu.queues',
                'path' => '/call-center',
                'icon' => 'queue',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'agents',
                'label_key' => 'menu.agents',
                'path' => '/call-center',
                'icon' => 'agent',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'wallboard',
                'label_key' => 'menu.wallboard',
                'path' => '/call-center/wallboard',
                'icon' => 'wallboard',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
        ],
    ],
    [
        'id' => 'crm',
        'label_key' => 'menu.sections.crm',
        'icon' => 'crm',
        'items' => [
            [
                'id' => 'crm_contacts',
                'label_key' => 'menu.contacts',
                'path' => '/crm/contacts',
                'icon' => 'users',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'crm_accounts',
                'label_key' => 'menu.crm_accounts',
                'path' => '/crm',
                'icon' => 'building',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'crm_activity',
                'label_key' => 'menu.activity',
                'path' => '/crm/activity',
                'icon' => 'activity',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
        ],
    ],
    [
        'id' => 'omnichannel',
        'label_key' => 'menu.sections.omnichannel',
        'icon' => 'messages',
        'items' => [],
    ],
    [
        'id' => 'provisioning',
        'label_key' => 'menu.sections.provisioning',
        'icon' => 'devices',
        'items' => [
            [
                'id' => 'phones',
                'label_key' => 'menu.phones',
                'path' => '/provisioning',
                'icon' => 'phone',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'provisioning_templates',
                'label_key' => 'menu.templates',
                'path' => '/provisioning',
                'icon' => 'template',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'phonebooks',
                'label_key' => 'menu.phonebooks',
                'path' => '/provisioning',
                'icon' => 'phonebook',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'provisioning_config',
                'label_key' => 'menu.provisioning_config',
                'path' => '/provisioning/config',
                'icon' => 'settings',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
        ],
    ],
    [
        'id' => 'billing',
        'label_key' => 'menu.sections.billing',
        'icon' => 'billing',
        'badge' => 'pending_invoices',
        'badge_tone' => 'danger',
        'items' => [
            [
                'id' => 'billing_dashboard',
                'label_key' => 'menu.billing',
                'path' => '/billing',
                'icon' => 'billing',
                'roles' => ['super-admin', 'reseller', 'admin-empresa'],
            ],
            [
                'id' => 'resellers',
                'label_key' => 'menu.resellers',
                'path' => '/billing/resellers',
                'icon' => 'reseller',
                'roles' => ['super-admin'],
            ],
            [
                'id' => 'subscriptions',
                'label_key' => 'menu.subscriptions',
                'path' => '/billing/subscriptions',
                'icon' => 'license',
                'roles' => ['super-admin', 'reseller'],
            ],
            [
                'id' => 'invoices',
                'label_key' => 'menu.invoices',
                'path' => '/billing/invoices',
                'icon' => 'receipt',
                'roles' => ['super-admin', 'reseller', 'admin-empresa'],
                'badge' => 'pending_invoices',
                'badge_tone' => 'danger',
            ],
            [
                'id' => 'usage',
                'label_key' => 'menu.usage',
                'path' => '/billing/usage',
                'icon' => 'chart',
                'roles' => ['super-admin', 'reseller', 'admin-empresa'],
            ],
        ],
    ],
    [
        'id' => 'security',
        'label_key' => 'menu.sections.security',
        'icon' => 'security',
        'badge' => 'security_attacks',
        'badge_tone' => 'danger',
        'items' => [
            [
                'id' => 'security_center',
                'label_key' => 'menu.security_center',
                'path' => '/security',
                'icon' => 'security',
                'roles' => ['super-admin', 'admin-empresa'],
                'permission' => 'security.view',
                'badge' => 'security_attacks',
                'badge_tone' => 'danger',
            ],
            [
                'id' => 'sip_attacks',
                'label_key' => 'menu.sip_attacks',
                'path' => '/security/attacks',
                'icon' => 'alert',
                'roles' => ['super-admin', 'admin-empresa'],
                'permission' => 'security.view',
            ],
            [
                'id' => 'blocked_ips',
                'label_key' => 'menu.blocked_ips',
                'path' => '/security/bans',
                'icon' => 'ban',
                'roles' => ['super-admin', 'admin-empresa'],
                'permission' => 'security.manage',
            ],
            [
                'id' => 'fail2ban',
                'label_key' => 'menu.fail2ban',
                'path' => '/security/fail2ban',
                'icon' => 'shield',
                'roles' => ['super-admin', 'admin-empresa'],
                'permission' => 'security.manage',
            ],
            [
                'id' => 'firewall',
                'label_key' => 'menu.firewall',
                'path' => '/security/firewall',
                'icon' => 'firewall',
                'roles' => ['super-admin', 'admin-empresa'],
                'permission' => 'security.manage',
            ],
            [
                'id' => 'whitelist',
                'label_key' => 'menu.whitelist',
                'path' => '/security/whitelist',
                'icon' => 'allow',
                'roles' => ['super-admin', 'admin-empresa'],
                'permission' => 'security.manage',
            ],
            [
                'id' => 'blacklist',
                'label_key' => 'menu.blacklist',
                'path' => '/security/blacklist',
                'icon' => 'ban',
                'roles' => ['super-admin', 'admin-empresa'],
                'permission' => 'security.manage',
            ],
        ],
    ],
    [
        'id' => 'integrations',
        'label_key' => 'menu.sections.integrations',
        'icon' => 'integrations',
        'items' => [
            [
                'id' => 'api_tokens',
                'label_key' => 'menu.api_tokens',
                'path' => '/settings/api-tokens',
                'icon' => 'api',
                'roles' => ['super-admin', 'admin-empresa'],
            ],
        ],
    ],
    [
        'id' => 'system',
        'label_key' => 'menu.sections.system',
        'icon' => 'server',
        'items' => [
            [
                'id' => 'realtime_engine',
                'label_key' => 'menu.realtime_engine',
                'path' => '/pbx/realtime',
                'icon' => 'pulse',
                'roles' => ['super-admin'],
                'permission' => 'pbx.view',
            ],
            [
                'id' => 'ami_ari',
                'label_key' => 'menu.ami_ari',
                'path' => '/pbx',
                'icon' => 'link',
                'roles' => ['super-admin', 'admin-empresa'],
                'company_only' => true,
            ],
            [
                'id' => 'advanced_settings',
                'label_key' => 'menu.advanced_settings',
                'path' => '/settings/profile',
                'icon' => 'settings',
                'roles' => ['super-admin', 'reseller', 'admin-empresa'],
            ],
        ],
    ],
];
